import React, { useState } from 'react';
import {
  Server,
  Terminal,
  Copy,
  Download,
  CheckCircle2,
  RefreshCw,
  Cpu,
  Zap,
  Shield,
  Activity,
  Save,
} from 'lucide-react';
import { useISP } from '../../context/ISPContext';

export const MikrotikConfigView: React.FC = () => {
  const { mikrotikConfig, updateMikrotikConfig, currentTenant, autoIsolirSettings } = useISP();

  const [host, setHost] = useState(mikrotikConfig.host);
  const [apiPort, setApiPort] = useState(mikrotikConfig.apiPort);
  const [username, setUsername] = useState(mikrotikConfig.username);
  const [password, setPassword] = useState(mikrotikConfig.password);
  const [useSsl, setUseSsl] = useState(mikrotikConfig.useSsl);
  const [copiedScript, setCopiedScript] = useState(false);
  const [testSuccess, setTestSuccess] = useState(false);
  const [isTesting, setIsTesting] = useState(false);

  // Generate RouterOS Script
  const generatedScript = `# ==============================================================================
# MIKROTIK ROUTEROS CONFIGURATION SCRIPT FOR ${currentTenant.name.toUpperCase()}
# Generated by MoniSys ISP Billing & Network Hub
# Core Gateway IP: ${host}
# ==============================================================================

# 1. SETUP FIREWALL ADDRESS-LIST UNTUK WEB ISOLIR
/ip firewall address-list
add list=${autoIsolirSettings.firewallAddressList} comment="Pelanggan Terisolir Otomatis Jatuh Tempo MoniSys"

# 2. SETUP NAT REDIRECT PORT HTTP/HTTPS KE HALAMAN WEB ISOLIR
/ip firewall nat
add chain=dstnat protocol=tcp dst-port=80 src-address-list=${autoIsolirSettings.firewallAddressList} \\
    action=dst-nat to-addresses=103.144.20.10 to-ports=80 \\
    comment="MoniSys Redirect Web Isolir HTTP"
add chain=dstnat protocol=tcp dst-port=443 src-address-list=${autoIsolirSettings.firewallAddressList} \\
    action=dst-nat to-addresses=103.144.20.10 to-ports=443 \\
    comment="MoniSys Redirect Web Isolir HTTPS"

# 3. SETUP FIREWALL FILTER (IZINKAN AKSES PORTAL PEMBAYARAN & DNS SAJA)
/ip firewall filter
add chain=forward action=accept protocol=udp dst-port=53 src-address-list=${autoIsolirSettings.firewallAddressList} \\
    comment="Izinkan DNS lookup untuk pembayaran"
add chain=forward action=accept protocol=tcp dst-port=53 src-address-list=${autoIsolirSettings.firewallAddressList} \\
    comment="Izinkan DNS TCP"
add chain=forward action=accept dst-address=103.144.20.0/24 src-address-list=${autoIsolirSettings.firewallAddressList} \\
    comment="Izinkan akses IP Server Portal Bayar MoniSys & QRIS"
add chain=forward action=drop src-address-list=${autoIsolirSettings.firewallAddressList} \\
    comment="Drop semua trafik internet umum pelanggan terisolir"

# 4. SETUP RADIUS CLIENT TERPUSAT
/radius
add address=10.10.10.5 secret="CitraNetRadiusKey2026" service=ppp,login authentication-port=1812 accounting-port=1813 \\
    timeout=3000ms comment="MoniSys Central AAA RADIUS"
/radius incoming
set accept=yes port=3799

# 5. SETUP PPPOE SERVER PROFILE DENGAN RADIUS
/ppp profile
add name="PROFILE_MONISYS_RADIUS" use-radius=yes dns-server=8.8.8.8,1.1.1.1 local-address=10.50.0.1
`;

  const handleCopyScript = () => {
    navigator.clipboard?.writeText(generatedScript);
    setCopiedScript(true);
    setTimeout(() => setCopiedScript(false), 2000);
  };

  const handleDownloadRsc = () => {
    const blob = new Blob([generatedScript], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `monisys_mikrotik_${currentTenant.slug}.rsc`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleTestConnection = () => {
    setIsTesting(true);
    setTimeout(() => {
      setIsTesting(false);
      setTestSuccess(true);
      updateMikrotikConfig({ host, apiPort, username, password, useSsl });
      setTimeout(() => setTestSuccess(false), 4000);
    }, 1200);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-white tracking-tight flex items-center gap-2.5">
            <Server className="w-6 h-6 text-indigo-400" />
            Integrasi MikroTik RouterOS Gateway
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            RouterOS API v7/v6 sync, auto firewall isolir address-list, dan generator script .rsc
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="px-3 py-1 rounded-full text-xs font-semibold flex items-center gap-1.5 border text-emerald-400 bg-emerald-500/10 border-emerald-500/20">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
            API RouterOS: Terhubung
          </span>
        </div>
      </div>

      {testSuccess && (
        <div className="p-3 bg-emerald-500/10 border border-emerald-500/30 rounded-xl text-emerald-400 text-xs flex items-center gap-2 animate-fade-in">
          <CheckCircle2 className="w-4 h-4 shrink-0" />
          <span>Koneksi RouterOS API berhasil terhubung dengan Router MikroTik: {mikrotikConfig.routerIdentity}!</span>
        </div>
      )}

      {/* Router Live Stats Card */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4">
          <span className="text-xs text-slate-400 flex items-center gap-1.5">
            <Server className="w-3.5 h-3.5 text-indigo-400" /> Identitas Router
          </span>
          <p className="text-sm font-bold text-white mt-1 font-mono truncate">{mikrotikConfig.routerIdentity}</p>
          <span className="text-[10px] text-slate-500 font-mono">{mikrotikConfig.host}:{mikrotikConfig.apiPort}</span>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4">
          <span className="text-xs text-slate-400 flex items-center gap-1.5">
            <Zap className="w-3.5 h-3.5 text-blue-400" /> Versi RouterOS
          </span>
          <p className="text-sm font-bold text-emerald-400 mt-1 font-mono">{mikrotikConfig.routerOsVersion}</p>
          <span className="text-[10px] text-slate-500 font-mono">Architecture: arm64</span>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4">
          <span className="text-xs text-slate-400 flex items-center gap-1.5">
            <Cpu className="w-3.5 h-3.5 text-amber-400" /> CPU Load
          </span>
          <p className="text-sm font-bold text-white mt-1 font-mono">{mikrotikConfig.cpuLoad}%</p>
          <div className="w-full bg-slate-800 h-1.5 rounded-full mt-2">
            <div className="bg-emerald-500 h-full rounded-full" style={{ width: `${mikrotikConfig.cpuLoad}%` }} />
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4">
          <span className="text-xs text-slate-400 flex items-center gap-1.5">
            <Activity className="w-3.5 h-3.5 text-purple-400" /> Uptime
          </span>
          <p className="text-sm font-bold text-white mt-1 font-mono">{mikrotikConfig.uptime}</p>
          <span className="text-[10px] text-emerald-400 font-mono">Stabil tanpa restart</span>
        </div>
      </div>

      {/* Settings & Script Generator */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Settings */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
          <h3 className="text-sm font-semibold text-white flex items-center gap-2">
            <Server className="w-4 h-4 text-indigo-400" />
            Pengaturan API RouterOS
          </h3>

          <div className="space-y-3">
            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1">IP Router / Host DDNS</label>
              <input
                type="text"
                value={host}
                onChange={(e) => setHost(e.target.value)}
                className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-xl text-xs text-white font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1">Port API (Default 8728)</label>
              <input
                type="number"
                value={apiPort}
                onChange={(e) => setApiPort(parseInt(e.target.value, 10))}
                className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-xl text-xs text-white font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1">Username RouterOS</label>
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-xl text-xs text-white font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1">Password RouterOS</label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-xl text-xs text-white font-mono"
              />
            </div>

            <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer pt-1">
              <input
                type="checkbox"
                checked={useSsl}
                onChange={(e) => setUseSsl(e.target.checked)}
                className="rounded border-slate-700 text-indigo-600"
              />
              <span>Gunakan API-SSL (Port 8729)</span>
            </label>

            <button
              onClick={handleTestConnection}
              disabled={isTesting}
              className="w-full py-2.5 px-4 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold transition-colors flex items-center justify-center gap-2 shadow-lg shadow-indigo-900/30"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${isTesting ? 'animate-spin' : ''}`} />
              {isTesting ? 'Menguji Koneksi...' : 'Uji Koneksi & Simpan'}
            </button>
          </div>
        </div>

        {/* Script Preview & RSC Generator */}
        <div className="md:col-span-2 bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <Terminal className="w-4 h-4 text-emerald-400" />
                Generator Script RouterOS (.rsc)
              </h3>
              <p className="text-xs text-slate-400">
                Script siap dieksekusi di Terminal MikroTik untuk konfigurasi Web Isolir, NAT, & RADIUS
              </p>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleCopyScript}
                className="px-3 py-1.5 text-xs font-semibold text-slate-200 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-lg flex items-center gap-1.5 transition-colors"
              >
                <Copy className="w-3.5 h-3.5 text-indigo-400" />
                {copiedScript ? 'Tersalin!' : 'Salin Script'}
              </button>

              <button
                onClick={handleDownloadRsc}
                className="px-3 py-1.5 text-xs font-semibold text-white bg-emerald-600 hover:bg-emerald-500 rounded-lg flex items-center gap-1.5 transition-colors shadow-sm"
              >
                <Download className="w-3.5 h-3.5" />
                Unduh .rsc
              </button>
            </div>
          </div>

          <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 font-mono text-xs text-slate-300 overflow-x-auto max-h-96 overflow-y-auto leading-relaxed">
            <pre>{generatedScript}</pre>
          </div>
        </div>
      </div>
    </div>
  );
};
